# Generated by Django 4.2.7 on 2023-11-19 20:49

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('course_number', models.IntegerField(default=0)),
                ('code', models.TextField(default='{}')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shared_link_author', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('body', models.TextField()),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('upvotes', models.IntegerField(default=0)),
                ('upvoted_user_ids', models.TextField(default='[]')),
                ('status', models.CharField(choices=[('PV', 'Draft'), ('PB', 'Published')], default='PV', max_length=2)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
                ('shared_link', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_shared_link', to='community.sharedlink')),
            ],
            options={
                'ordering': [django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('upvotes'), '+', models.Value(1)), '*', models.Value(-1)), '/', django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.ExpressionWrapper(django.db.models.expressions.CombinedExpression(models.Value(datetime.datetime(2023, 11, 19, 20, 49, 35, 678434, tzinfo=datetime.timezone.utc)), '-', models.F('publish')), output_field=models.IntegerField()), '/', models.Value(86400000000)), '+', models.Value(1)), '^', models.Value(3))), '-publish'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('upvotes', models.IntegerField(default=0)),
                ('upvoted_user_ids', models.TextField(default='[]')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='community.post')),
            ],
            options={
                'ordering': ['-upvotes', 'created'],
                'indexes': [models.Index(fields=['-upvotes', 'created'], name='community_c_upvotes_219245_idx')],
            },
        ),
    ]
