# Generated by Django 4.2.7 on 2023-11-20 01:00

import datetime
from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': [django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('upvotes'), '+', models.Value(1)), '*', models.Value(-1)), '/', django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.ExpressionWrapper(django.db.models.expressions.CombinedExpression(models.Value(datetime.datetime(2023, 11, 20, 1, 0, 28, 168555, tzinfo=datetime.timezone.utc)), '-', models.F('publish')), output_field=models.IntegerField()), '/', models.Value(86400000000)), '+', models.Value(1)), '^', models.Value(3))), '-publish']},
        ),
    ]
